# Generated by Django 6.0.1 on 2026-01-28 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HaradaChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('core_goal', models.TextField(help_text='The long-term goal')),
                ('target_date', models.DateField()),
                ('is_draft', models.BooleanField(default=True, help_text='True while completing wizard steps')),
                ('perspectives', models.JSONField(default=dict, help_text='Four perspectives: self_tangible, self_intangible, others_tangible, others_intangible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harada_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(help_text='Position 1-8 around the center cell', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.haradachart')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('chart', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('routine', 'Routine')], default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('position', models.IntegerField(help_text="Position 1-8 within the pillar's 3x3 grid", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.haradachart')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.pillar')),
            ],
            options={
                'ordering': ['pillar', 'position'],
                'unique_together': {('pillar', 'position')},
            },
        ),
    ]
