# Generated by Django 6.0.1 on 2026-01-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillar',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('indigo', 'Indigo'), ('orange', 'Orange')], default='blue', help_text='Color for this pillar and its tasks', max_length=20),
        ),
    ]
